### ISSUE TITLE
[Project][feedback] Provide feedback on my Portfolio

### ISSUE THREAD

**Issue by 4nmolChaudhary** [tanaypratap/teamtanay.jobchallenge.dev#251]
https://4nmolchaudhary.github.io/
👆🏻 this is my portfolio link please take a look once and provide feedback on it.

**Comment by anurag-majumdar** [comment]
Hi, can you also share the link to the source code?

**Comment by 4nmolChaudhary** [comment]
> Hi, can you also share the link to the source code?

https://github.com/4nmolChaudhary/4nmolChaudhary.github.io

**Comment by anurag-majumdar** [comment]
Hey @4nmolChaudhary I went through your project in detail!

Your site looks quite impressive in terms of content and thought process!
However, kindly note down the following important points:

This project challenge tests the originality of thinking of the student. How the student approaches an idea with design as well as development. We cater to & review according to the project ideas as well.

**Product Thinking:**
It came to notice that most of the design components used for this site are exactly similar to [fireship.io](https://fireship.io/).
A portfolio is very useful to show to recruiters and definitely an important tool to be showcased worldwide in order to show your skills. Kudos on the thought of making a portfolio!

**UI/UX:**
Since the colours and design are exactly similar to [fireship.io](https://fireship.io/) , we cannot evaluate on this aspect even though the colour contrast usage is perfect here. Even the hover effects, card components are similar in design. Once again, we stress on the originality of a student's idea.

**Code & Scalability:**
1. All code is written in html & css mostly, good usage of css variables and class names.
2. Try avoiding use of inline styles in the html files and use classnames or ids to provide styles. This will make your css more scalable.
3. The site has a sidenav with links and main content area. It can be seen that each html file (about, projects etc.) has the same svg images, sidenav content which make the code a bit larger in size for each file.

Hint: Try keeping one sidenav in index.html and according to link clicks load the corresponding content into html. (You can load html files via async requests too).

**Content:**
I personally loved the usage of content in the site. Especially the skills area, you broke it up into different areas of development. Even the about page with the timeline design. Kudos!
Try to keep the same content but do remember to change the overall design and the individual component designs.

**Improvements:**
1. To maintain originality of a student's project, we would like to request you to come back with a new design (something which is unique, not necessarily flashy), colour scheme and thought process of the skeleton of the site. The individual content of your site looks fine (ex: project, about pages).
Try to come up with a different overall look, feel and layout of the site. You don't need to change the content of individual pages, just focus on the look and feel.

2. The site looks more or less responsive with a few distortions here and there while expanding the site from 300px to max resolution. A mobile device can have at the minimum 300px of width. While developing a responsive site, make fixed widths less than 300px for the smallest devices.
Also, in meta viewport tag, use **"initial-scale=1"** in html pages, instead of using **"minimum-scale=1"**. This should help fix the zoomed out issue in mobile devices and stop the browser in deciding the zoom of the site.

3. Make the site is more scalable by trying to have only one sidenav in code, try not to put the sidenav in other pages (project, about). This will ensure a performance boost during your load time on link clicks by eliminating redundant code in every page. Try working on this area, it will help you to get bonus points for scalability.

4. Try avoiding the usage of inline styles and create class names for respective classes.

5. Try to make sure no grammar issues, no spelling issues & no inappropriate words are there in your portfolio (ex: "Who's the hell is this guy ?" instead use similar to this: Woah! Who is this guy? ).
Remember, usage of informal expressions portray your personality and flair, this is a killer area for the recruiter to get to know your personality even before meeting you, so use it wisely. 😄 

We look forward to evaluating what changes and original thinking you can bring about in the project. Try accumulating ideas from everywhere, but make sure not to replicate the exact site design, rather come up with your own design. 👍

**Comment by 4nmolChaudhary** [comment]
Thank You so much for your kind and honest review,
I will be looking forward to improve the required changes and come up with a new design
@anurag-majumdar 👍

**Comment by 4nmolChaudhary** [comment]
Here is my new Portfolio Link
https://anmolchaudhary.netlify.com/
It is created using Gatsby
**Please Respond**

**Comment by 4nmolChaudhary** [comment]
@4nmolChaudhary

**Comment by 4nmolChaudhary** [comment]
@anurag-majumdar  Please **RESPOND**

**Comment by anurag-majumdar** [comment]
@4nmolChaudhary Please wait patiently as the review process is undergoing currently. Expect to receive your feedback within a day.

**Comment by anurag-majumdar** [comment]
Thank you for being patient. Here is your review of the site:

**UI/UX:**
Great choice of colours. You have decided to keep the simple approach in terms of colour choice which is quite classy. Your design looks clear and crisp. Definitely an eye catcher.

Your site is also fully responsive without most of the glitches. While reviewing the flexibility of the site, I found that your pages don't have fixed height for the navbar area (your image section) on top with a margin. You can work on this area to fix the issue such that your main content doesn't overlap with the navbar area in future.

This is how it looks when the height of the browser is shrinked:

![image](https://user-images.githubusercontent.com/13219942/78299632-e270cc80-7553-11ea-913c-6250654ec9de.png)

**Code & Scalability:**
Great to see usage of Gatsby and it's static templates into your project. You've added a new skill in the process too. Bonus marks for trying out a new approach to problem solving here.

These templates make it easier to generate content from already existing ideas and help us abstract out the more difficuilt coding areas mostly.

**Content:**
As I mentioned before, I personally loved the usage of content in the site. You have definitely improved it and made it a little better.

You have improved on most of the points. It's great to see your learning process with us at the same time. We can clearly see your strength lies towards designing an application. Some of the challenges might have been more difficult code wise, but great job in atleast trying to figure out a few of them.

**Comment by 4nmolChaudhary** [comment]
Thank you for your kind review @anurag-majumdar
