### ISSUE TITLE
[Blog][Feedback] Please provide review on the Blog What is Redux?

### ISSUE THREAD

**Issue by swapnadeepmohapatra** [tanaypratap/teamtanay.jobchallenge.dev#282]
## What is Redux?
I tried to make people understand people what is Redux by taking some real-life examples.
Kindly read this blog and suggest some improvements.
 
https://medium.com/@swapnadeep456/what-is-redux-d8a131bc0402

Thank you

**Comment by tripsus** [comment]
Hi,
I went through your blog post. I am not a frontend developer so giving my perspective form someone who wants to learn Redux. Blog is nicely formatted and content is nice and clear. Few suggestions.
1. Consider using arrow in the image where you describe how redux work using the law example. This will give the readers understanding of flow without having to go through text.
2. Second paragraph in conclusion section is little unclear. Please re-phrase so that it is easily understandable.

**Comment by swapnadeepmohapatra** [comment]
Thank you Sushil for your suggestions. I will surely do so.
