### ISSUE TITLE
[Portfolio][Feedback][Code review] Please provide feedback for my project.

### ISSUE THREAD

**Issue by chintankamani** [tanaypratap/teamtanay.jobchallenge.dev#326]
Hey reviewer,

Could you provide feedback on my portfolio?
[Link]: [https://chintankamani.github.io/portfolio/](url)
[Repo]: [https://github.com/chintankamani/portfolio](url)

Thanks for taking the time!

**Comment by Shriram-Balaji** [comment]
@chintankamani The portfolio looks really good! Very creative, and loved the warp effect on loading. Animations on every transition also seem smooth. All your projects and work are also neatly showcased. You've used plain JS without relying on libraries or frameworks, which is great.

I did a quick skim of the codebase as well, and everything looks good to me. It's structured and also quite readable.

**Suggestions**
- Make the width of the about-me cards equal on mobile. (This could be a nitpick, because the styles on the rest of site looks good on smaller displays as well :smiley: ) 
![image](https://user-images.githubusercontent.com/11358903/78507437-91ecaf80-779d-11ea-9da9-c9217070b4bd.png)

- maybe add `mailto` link to your email address

 Kudos on the effort!

**Comment by chintankamani** [comment]
@Shriram-Balaji 
Thanks for taking the time to review it!
I appreciate the feedback.
I also fixed the suggestions you mentioned.

Thanks
