### ISSUE TITLE
[Project Review] Up Service

### ISSUE THREAD

**Issue by manjots1607** [tanaypratap/teamtanay.jobchallenge.dev#647]
### Description
**Up Service** is built on top of express JS and node JS and I used mongo DB as database for this project.
This project helps businesses to provide best service to their customers as it manages calls received through customers by call center executive if issue is not solved it is passed to engineer by default exec can choose from engineers having lowest number of pending calls and after that engineer has two option either close or pass call to another engineer if he is unable to solve issue.

There is also admin role who can view various stats and creating id's of new CC Exec's and Engineers.
App link:- http://vast-cove-92856.herokuapp.com/
Source link:- https://github.com/manjots1607/up-service

###Credentials
If you are going to review this project you need credentials that are following:-
1. Admin:
        username: admin@upService
        password: 123@adminPassword
2.Call Center Exec:
        username: callcenter1@abc.com
        password: password
3. Engineer:
        username: engineer2@abc.com
        password: password

**Comment by manjots1607** [comment]
Please review @tanaypratap @ameerthehacker @anurag-majumdar

**Comment by ameerthehacker** [comment]
@manjots1607 I apologise for the delay, got caught up with work recently, will be reviewing your project soon

**Comment by manjots1607** [comment]
No issue man @ameerthehacker , its still great of you all,  that you are working for us to have better career. 🙂🙂

**Comment by ameerthehacker** [comment]
@manjots1607 well done!
I liked the UI and the problem your trying to solve with the modern look

Thinks that I loved:
* Good choice of colors
* dashboard showing some analytics and quick actions
* Home page is neat
* Single login for every users

Thinks that can be improved:
* When I login with a wrong username and password it does not say anything and redirects to home page
* When there is a validation error in one of the form it threw a JSON at me rather than a pop up
![Screenshot 2020-06-27 at 1 21 53 PM](https://user-images.githubusercontent.com/15448192/85917743-7532b600-b87a-11ea-9892-36ab928db45a.png)
* Could have been a SPA (just a suggestion but it is not a deal breaker)
* Little bit more spacing between label and radio buttons
![Screenshot 2020-06-27 at 1 23 30 PM](https://user-images.githubusercontent.com/15448192/85917756-8da2d080-b87a-11ea-8c4e-b63807fde71e.png)

Overall really great effort and well done!

**Comment by manjots1607** [comment]
Thanks for Review Sir, means alot and it is detailed For Validation I will use flash module to handle it and will improve spacing and will try to give look to UI for more improvements.
